# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('date', models.IntegerField()),
                ('content', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'event_comment_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'event_info_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventLike',
            fields=[
                ('event_id', models.IntegerField(primary_key=True)),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.IntegerField()),
            ],
            options={
                'db_table': 'event_like_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('event_id', models.IntegerField(primary_key=True)),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.IntegerField()),
            ],
            options={
                'db_table': 'event_participate_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('src', models.ImageField(max_length=500, upload_to='images/')),
            ],
            options={
                'db_table': 'photo_of_event_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'session_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_info_tab',
                'managed': False,
            },
        ),
    ]
